### ISSUE TITLE
Pretty printing of Absyn in error message does not respect fixity

### ISSUE THREAD

**Issue by JohnReppy** [smlnj/smlnj#141]
### Version

110.82

### Operating System

- [X] All
- [ ] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### Processor

Any

### Component

Core system

### Severity

Cosmetic

### Description of the problem

The error message prints '::' as a prefix operator, instead of as an infix operator.  This behavior is a regression, since previous versions got it right (see tests/bugs/outputs/bug0027.out for example).

### Transcript

```
Standard ML of New Jersey v110.82 [built: Sat Oct 14 13:08:58 2017]
- fun f [] = 0
=   | f (x::xs) y = 1;
stdIn:1.6-2.20 Error: clauses don't all have same number of patterns
stdIn:1.6-2.20 Error: parameter or result constraints of clauses don't agree [tycon mismatch]
  this clause:      'Z list * 'Y -> 'X
  previous clauses:      'W list -> 'X
  in declaration:
    f = (fn nil => 0
          | (:: <pat>,y) => 1)
```

### Steps to Reproduce

fun f [] = 0
    | f (x::xs) y = 1;

#### Original smlnj-gforge bug number 204

Submitted  on 2018-37-19 at 14:3700

**Keywords:** Pretty printing

**Comment by dmacqueen** [comment]
Fixed in 2022.1 (as well as smlnj/legacy).  Used new function AbsynUtil.headStripPat in PPAbsyn..ppDconPat to strip MARKpat from the argument pattern in the APPpat case of ppDconPat'.  Fix modifies ElabData/syntax/ppabsyn.sml and absynutil.sml.  Also moved some PPAbsyn debug and print flags to ElabDataControl (ElabData/main/edcontrol.*.
