### ISSUE TITLE
Lightweight IDE for SML/NJ

### ISSUE THREAD

**Issue by AGoh2019** [smlnj/smlnj#270]
### Description

Hi,  I believe that the team behind SML/NJ should quicken up and produce a lightweight IDE.  Just got some disconcerting news from someone who knows Microsoft that it isn't developing the F# Language Server.  Not sure if F# will be dropped.  The other alternative, OCaml in the Windows variant isn't stable yet for production use.  And the SML/NJ command-line interface isn't enticing to use at all.  Maybe, next time, the open source community should impress on language developers to also provide a IDE when they launch a new computer language.

**Comment by JohnReppy** [comment]
I agree with Matt that LSP is the right solution to this problem.  I've played with Millet a bit and it does provide some CM support.  One thing that is on our TODO list is to change the mechanism used by CM to pickle environment information to an ASDL-generated pickler.  This change will make it possible to tools like Millet, which is written in Rust, to get access to the CM dependency info directly.

For the record, SML was introduced in the 1980s (first version of the language specification was published in 1990).  IDEs were not a thing at that time (although there was active research on structured editors).

**Comment by ratmice** [comment]
That is really interesting, I've been tinkering (nothing released) with a build system which uses json-ld as it's schema language (implemented in rust) for no language in particular. Anyhow it is really interesting to consider how I would encode CM tools like the registerShellCommand calls such as in ml-yacc https://github.com/smlnj/smlnj/blob/main/tools/ml-yacc/tool/tool.sml#LL21C46-L21C46 into the whole dependency graph.  I'm somewhat curious if there are any e.g. pure sml tools (rather than declaring shell commands) which generate code which wouldn't be easy to encode into the dependency graph.

Given CM's flexibility this does seem more difficult than one might initially anticipate! Anyhow it does sound fairly interesting.
In the system i've been working on the equivalent of CM's tools are implemented in web assembly, somewhat avoiding the "pickling code" issues.

**Comment by dmacqueen** [comment]
Regarding IDEs in the 1980s: I had experience with a couple of Lisp-based early IDEs, namely the Interlisp system on the Dec 10/20, and the Symbolics Lisp Machine. These did not leave a lasting positive impression -- emacs is still my IDE, and the type checker is my debugger.

Sam Westrick's smlfmt system looks interesting, and is more accessible than Millet as it is implemented in SML rather than Rust. I plan to look at the smlfmt parser as a potential replacement for the mlyacc-generated parser we use in SML/NJ, since it provides better syntax error messages. I may also borrow one of the innovative ideas (scoped tabs) from its formatter (prettyprinter for SML code).

On a side note, I have recently been working on a personal project to understand, and possibly rework, the CM system. I started by spending a couple of weeks understanding and simplifying the SrcPath structure (cm/paths/srcpath.s??).  The CM implemention
and documentation could use some work, and the related SML/NJ bootstrap process needs to be clarified and documented.  It is possible that CM could be made more "transparent" and "interoperable" (with smlfmt, and IDE?), but it will take significant effort.

**Comment by JohnReppy** [comment]
smlfmt is not an LSP server, so I don't see how it addresses the IDE issue.

**Comment by JohnReppy** [comment]
Since LSP is just a communication protocol, there is no reason that the server (or the editor) has to be written in the language that it supports.  Eventually, I'd like to see an LSP server written in SML, but we need a more modular design for the front-end of the compiler to support such a thing.

**Comment by dmacqueen** [comment]
> Since LSP is just a communication protocol, there is no reason that the server (or the editor) has to be written in the language that it supports. Eventually, I'd like to see an LSP server written in SML, but we need a more modular design for the front-end of the compiler to support such a thing.

I have been working toward "a more modular design for the front-end" for a while, mainly the elimination of FLINT intrusions into the front-end code. This will continue with substantial rewrites of the type checker and module system over the next couple years. But I am not quite sure where the current front end is not modular enough to support the implementation of an LSP server. Last time I thought about this, it seemed to be a matter of translating information contained in various internal representations into a form that would be communicated using the LSP protocol.  But I have not learned the details of the LSP protocol, so I don't know what the difficulty level would be.

**Comment by ratmice** [comment]
One benefits and reasons i've been writing language server based projects in rust is it's support for web assembly which is difficult in sml due to GC currently. The thought behind this is that it gives easy install-free access to a fully featured ide, on things such as https://github.com/codespaces from the browser.  Millet doesn't appear to currently compile to web-assembly as far as I can tell, but it is currently a lot easier to do with rust than it would be in sml, and as John says it is just a communication protocol between the server and the editor.

To me it seems worthwhile experimenting with such things in classrooms, if it pushes things like installation and setup on a local machine to an optional thing people *can* do if they prefer it...

**Comment by JohnReppy** [comment]
Matt:

GC for Web Assembly seems to be coming.  But there are also a couple of web-based SML implementations.  The SMLtoJS ("SML Toys") based on the SMLKit compiler and the online interpreter for SML at https://sosml.org/.

**Comment by JohnReppy** [comment]
Dave:
Modularity means being able to use the parser and type checker as components of another system (e.g., a LSP server).  Pulling the scanner/parser out is pretty easy, but the elaborator seems more difficult.

**Comment by ratmice** [comment]
> Matt:
> 
> GC for Web Assembly seems to be coming. But there are also a couple of web-based SML implementations. The SMLtoJS ("SML Toys") based on the SMLKit compiler and the online interpreter for SML at https://sosml.org/.

Indeed, I just wanted to justify why i think rust is a good choice *now*. Sosml/SMLtoJS are nice, but not something that I would want to install on my local machine and replicate the exact editor environment for my every day coding in.  Anyhow it is perhaps kind of off topic (sorry) and feel i've gotten my point across.

**Comment by dmacqueen** [comment]
> Dave:
> Modularity means being able to use the parser and type checker as components of another system (e.g., a LSP server). Pulling the scanner/parser out is pretty easy, but the elaborator seems more difficult.

If you look at the newpp branch, the library structure of the front-end (and the rest of the compiler) has been clarified and completed by the addition of some missing CM library description files (Parse/parser.cm, FLINT/flint.cm, etc.). The elaborator consists of the two CM libraries ElabData/elabdata.cm and Elaborator/elaborate.cm. These depend on the libraries Basics/basics.cm and Parse/parser.cm. The detailed dependencies within and between these libraries are documented in corresponding MAP files (Basics/MAP-Basics.txt), Parse/MAP-Parse.txt, ElabData/MAP-ElabData.txt, and Elaborator/MAP-Elaborator.txt).  It would be useful if these MAP files could be machine generated (presumably by CM) and machine readable. These MAPs are at a module level of granularity. We might also hope for finer, function-level dependency information, and function-level indexing, e.g. something like function "foo" --> structure S --> source file $Elaborator/A/s.sml. Of course, function names can be ambiguous
(S.foo, R.foo), so you would either need to qualify the function name or have a one-to-many index.

**Comment by dmacqueen** [comment]
This feature (using compiler components as libraries) hasn't been tested and debugged (can't bootstrap my branch at the moment), but I am confident that it can be made to work.
