### ISSUE TITLE
Wrong description of brace syntax in RegExp Library in SML of NJ Library

### ISSUE THREAD

**Issue by rgizz** [smlnj/smlnj#289]
### Version

2024.1 (latest)

### Operating System

- [X] Any
- [ ] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other Unix

### OS Version

Any OS: this is documentation

### Processor

- [X] Any
- [ ] Arm (using Rosetta)
- [ ] x86-64 (64-bit)
- [ ] Other

### System Component

Documentation

### Severity

Minor

### Description

Documentation of repetition match brace regexp, under the AwkSyntax structure, reads as follows: 
A{n,}	matches n copies of A
A{n,m}	matches n copies of A
This is inaccurate

### Transcript

Not applicable to documentation issue

### Expected Behavior

I suggest this, which I took from Perl's documentation:
A{n,} = match at least n or more times
A{n,m} = match at least n times, but not more than m times.

### Steps to Reproduce

Not applicable. This just has to do with the current documentation on SML/NJ's web page. 

### Email address

gztown2216@yahoo.com

**Comment by JohnReppy** [comment]
From my quick testing, these examples work fine with the `BackTrackEngine`; the `ThompsonEngine` fails on the last example, and the `DFAEngine` is more seriously broken.  I'm currently working on fixing the `ThompsonEngine`, since I wrote that one.  The `DFAEngine` probably needs a complete rewrite.

I will push a correction to the documentation.

**Comment by JohnReppy** [comment]
A fix for the bug part of this issue has been pushed.
